### ISSUE TITLE
log timestamp delay

### ISSUE THREAD

**Issue by kyauaa** [graylog-labs/graylog-plugin-dnsresolver#5]
After I install and run this plugin , I found that new logs' timestamp would delay 20 mins offset. Does anyone face the same issue?

**Comment by joschi** [comment]
@kyauaa This plugin doesn't modify the "timestamp" message field, so maybe your DNS resolvers are slow?

Although 20 minutes would be quite long…

You can check the runtime metrics of the DNS Resolver filter to see, if the problem lies there:
* `org.graylog.plugin.filter.dns.DnsResolverFilter.resolveTime`
* `org.graylog.plugin.filter.dns.DnsResolverFilter.resolveTimeouts`

**Comment by kyauaa** [comment]
Hi Joschi. Thanks for your reply. I have changed my DNS setting, and it works properly now. Thank you so much.
